#!/usr/bin/env bash

START_ROUND_6=10245999
END_ROUND_6=10309068
#END_ROUND_6=latest

#export NO_COLOR=true
export API_MODE=true
export NO_SCHEMAS=true
export NO_PROGRESS=true
#export TEST_MODE=true
export HIDE_NAMES=true

chifra list $2 --start $START_ROUND_6  --end $END_ROUND_6 | grep -v "\"address\"" | jq '.' >appearances/$1/$2.json
chifra export $2 --accounting --articulate --write_txs --ether --start $START_ROUND_6 --end $END_ROUND_6 | jq '.' >transactions/$1/$2.json
chifra export $2 --logs --articulate --start $START_ROUND_6 --end $END_ROUND_6 | jq '.' >logs/$1/$2.json

#cat appearances/$1/$2.json | grep -v staging | grep -v ripe | grep -v "FromAndTo\": {}," | sed 's/\"finalized\": 10331760,/\"progress\": \"not reported\",/' >x
#cat x >appearances/$1/$2.json
#echo $1/$2
#
#cat transactions/$1/$2.json | grep -v staging | grep -v ripe | grep -v "FromAndTo\": {}," | sed 's/\"finalized\": 10331760,/\"progress\": \"not reported\",/' >x
#cat x >transactions/$1/$2.json
#echo $1/$2
#
#cat logs/$1/$2.json | grep -v staging | grep -v ripe | grep -v "FromAndTo\": {}," | sed 's/\"finalized\": 10331760,/\"progress\": \"not reported\",/' >x
#cat x >logs/$1/$2.json
#echo $1/$2

echo

sleep .2
