#!/usr/bin/env bash

#export NO_COLOR=true
#chifra list $2 --fmt json | grep -v "\"address\"" | jq >appearances/$1/$2.json
#sleep .2

export NO_COLOR=true
export API_MODE=true
chifra export --articulate $2 | jq >transactions/$1/$2.json
sleep .2
