#!/usr/bin/env bash

START_ROUND_6=10245999
END_ROUND_6=10309068
#END_ROUND_6=latest

#export NO_COLOR=true
export API_MODE=true
export NO_SCHEMAS=true
#export TEST_MODE=true
export NO_NAMES=true

chifra list $2 --start $START_ROUND_6  --end $END_ROUND_6 | grep -v "\"address\"" | jq '.' >appearances/$1/$2.json

chifra export $2 --accounting --articulate --write_txs --ether --start $START_ROUND_6 --end $END_ROUND_6 | jq '.' >transactions/$1/$2.json

chifra export $2 --logs --articulate --start $START_ROUND_6 --end $END_ROUND_6 | jq '.' >logs/$1/$2.json

echo

sleep .2
