#!/usr/bin/env bash

cd appearances/core
gunzip --force --verbose --keep *.gz
cd -

cd appearances/grants
gunzip --force --verbose --keep *.gz
cd -

cd transactions/core
gunzip --force --verbose --keep *.gz
cd -

cd transactions/grants
gunzip --force --verbose --keep *.gz
cd -

cd logs/core
gunzip --force --verbose --keep *.gz
cd -

cd logs/grants
gunzip --force --verbose --keep *.gz
cd -
