#!/usr/bin/env bash

cd appearances/core
gzip *.json
cd -

cd appearances/grants
gzip *.json
cd -

cd transactions/core
gzip *.json
cd -

cd transactions/grants
gzip *.json
cd -

cd logs/core
gunzip *.json
cd -

cd logs/grants
gunzip *.json
cd -
